# You can pick any Debian/Ubuntu-based image. 😊
FROM mcr.microsoft.com/devcontainers/base:bullseye

# [Option] Install zsh
# ARG INSTALL_ZSH="true"
# COPY library-scripts/*.sh /tmp/library-scripts/
# RUN bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true" \
# Install the Azure CLI
# && bash /tmp/library-scripts/azcli-debian.sh \
# Clean up
# && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts



